development:
  bucket: <%=ENV["S3_BUCKET_NAME"]%>
  access_key_id: <%=ENV["AWS_ACCESS_KEY_ID"]%>
  secret_access_key: <%=ENV["AWS_SECRET_ACCESS_KEY"]%>
  url: https://<%=ENV["S3_BUCKET_NAME"]%>.s3-us-west-2.amazonaws.com/

test:
  bucket: <%=ENV["S3_BUCKET_NAME"]%>
  access_key_id: <%=ENV["AWS_ACCESS_KEY_ID"]%>
  secret_access_key: <%=ENV["AWS_SECRET_ACCESS_KEY"]%>
  url: https://<%=ENV["S3_BUCKET_NAME"]%>.s3-us-west-2.amazonaws.com/

production:
  bucket: <%=ENV["S3_BUCKET_NAME"]%>
  access_key_id: <%=ENV["AWS_ACCESS_KEY_ID"]%>
  secret_access_key: <%=ENV["AWS_SECRET_ACCESS_KEY"]%>
  url: https://<%=ENV["S3_BUCKET_NAME"]%>.s3-us-west-2.amazonaws.com/