development:
  adapter: postgresql
  database: tandem_staff
  username: macuser
  host: localhost
  port: 5432
  pool: 10
test:
  adapter: postgresql
  database: tandem_staff_test
  username: macuser
  host: localhost
  port: 5432
  pool: 10