development:
  adapter: postgresql
  database: staff_portal
  username: macuser
  host: localhost
  port: 5432
  pool: 10
test:
  adapter: postgresql
  database: staff_portal_test
  username: macuser
  host: localhost
  port: 5432
  pool: 10