#
# Symmetric Encryption for Ruby
#
---
# For the development and test environments the test symmetric encryption keys
# can be placed directly in the source code.
# And therefore no RSA private key is required
development:   &development_defaults
  key:         1234567890ABCDEF1234567890ABCDEF
  iv:          1234567890ABCDEF
  cipher_name: aes-128-cbc
  encoding:    :base64strict

test:
  <<: *development_defaults

release:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEA12f6sQzbb7kzkh5nFl+OFGRKKHVnxe215Zb2M7aBSlMBiseV
    VHRZRnIZ3t/hd1JAt8NDzU96wWlqbYm1laGTPmRSTvx3ydz3oBcuEViK5D0aoRJ9
    5wFu3ArPZec6KXTsjFrYLjsUWCbKdAqcVGPQsM6eiSc6fJBiZpK78/YjnUuAglS/
    RL9y5fGcXo4Fq1nYJac52mW/yljzXLMsBlCRDf+vhmGjuo00ciyWnIW47NcNPjXu
    IsnLOA4hDsEpIYdi4ZXave/TBXNH45AncYopRs1pzQ838IwDmLgR4iF1oTAypvLA
    lfzEoANMf56UpJV+cxQ41J7hFxl+M/UbGEAGFwIDAQABAoIBAC2kw9NGdS0cYlgh
    BxkPkGyzv58JGb8wGq4Wqf7VOlpEcnw0xGjL6qrpvJ+kcwM0s6/8uV5E7C8Vpk6l
    souNXEUJPwOrrbphjzsmDkXwrCWm6QCeiX0sqZAI3l+qeoGUXBd1nH9XV31CYv3p
    zax4Jh2A+sj3PgZtFdzEVP1h97P5itmv19iXBe24gw8ao9Dpizy0iqq4CWrVdH09
    w2K3IF1ONOrJvR27v4gp7EapBDS0MMIXGiMbCHZirlSSdQ3CRJqOdtsOX6/YKv+k
    fdOgScsHRGifg992d4cAL9z5BepIC4dCwM9CMKV6GWWk6fK62Tb2pn/Ays4+Lrjv
    86We+uECgYEA/ypPN0miXGifL7/8wJ5DfG2kK2fEgtUrRl/phMZxsTrGhS4A2P7d
    g80QPv+OpIWA0PGF1R8GvijrVx/uYLdWm5AFait/eczT7cKEFbALhZmNtNH3w8ik
    Xt5fvjP+JaiLrAO8Gdj/5CfCIUGc/PQY810U1cqU/f8Qpxo6ea1KXMcCgYEA2Bxf
    iXwMBsBOCnstwwEBj7fLeDOlA8IBr18AiithY5+07jr7PO0cmKBdWkaAfjRW9uNy
    prxAVwK6EU6Am9YQN3DFyBbnrgjJoBK26WaJZbshAWTVVqSED3k4nz2GDLdwyKVY
    wP0fF9D3UpYP570UvVeELjeHlOmZJW0wI8atnDECgYEAkLNAmvzR6w+VfnGkduMJ
    KE3Q9KBy6zLRyKXpeldC8BuBqtLMvkHCAtVOajtoe9oNk+/zUkm2/C2eUBkWiJhP
    sAY7W9rw/nRuln1hhB8CWbAbkTglBk0JEZePugAoFtj+4/x2Nj491vfI+i0IRtZy
    M8hMYXTxixyTKAASux/PdM8CgYEAo+XI0vUgDdK0nSBUUWsm6v9CMdRBFruBGaac
    Oy2xO6P4zSAwQEG3iU0932ROuOgq+C0BW9CznwmzYcK+qPFM9S7y4M/2Pzfs6hin
    XhXkqCGmY288mOxGN5IAzkwTqPtKbvFvgVW2yhIyMBEc2Oy+mOaRmZeFnPsYqZjI
    hKl+K1ECgYEA9CZPmaJUz5QXdu6nCpG3/JDtAr4BR2FEl9oUnRFAWpm1kKClrPhV
    CgnMXxAkGZga06ykGv9TFqiS2EbtWFDwumHPdwXpDr2TdAYAwJg8kw6aARtLbfsn
    rAmaGxmb86z0437qIV5C9uG9ulH/rJKu3LXmU6PgB6gRnNM8F6oQjXs=
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      encrypted_key: "<%= ENV['RELEASE_KEY1'] %>"
      iv:            "TdVPwj8QMSVWy/TiZ1TnxQ=="
      cipher_name:   aes-256-cbc
      # Base64 encode encrypted data without newlines
      encoding:      :base64strict
      version:       1

production:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAzZ+9J1kE1QORHrf3CwOR9mhEhSfw6IFwbI3yhrTWM5dyqeY+
    VDFPhGpcMgtvWy6VFo0NW+9X6vFByWk961ErTFHu/90jOsD6Sl6Y/m/l1aQ6OsJl
    KW6QA0FWtxHjj3XFQoFusCztj4v16+LeEjC2GPfZZh9N92t/FchmszQKBtd88/2y
    kEYsl2BzMWQ8CE3pH3UqN1GNBjHBCr4SRPlkDoMltficKYjY8a/JClA1F0noZ9bF
    zIX9ctP5zZ6x+d9/XcYLMyoGWhVQ3YdksETNVpspiaTL08n/5A+YJLm7KmuSEUfn
    1Pul/pF/BI8QiGTxDuDkYYctJaGNiD2/ewy5YQIDAQABAoIBAQCCjJ2igsEvoREd
    CL2/b2fXowGF7QLmC3Bea40Ee4HXxZrWRcli2N/ceU7JszrjEGM1qx5FNWODVeNn
    xfq7EZDE5uwv5K2+WtFOMFtAh7jLeHZD4jIqKPkkJ/KvTptE9QflnpmxHwVA8yKS
    vjoyIF0s4wdS8CMnKEfKg664rhyDlF4KfM5bhvYJ76ns35bQlOmZURo1DGlS0bbl
    +MDUkgh7gE9/hGz1swgdrh+rgwekQwLrooe5fN5IXVAdTxKv8mtqeV1ITuHsG+PH
    bUefRagrsXeQvUc/luH1J7YGUUtaGmy6gYYwdSyyh0qGp0l/w2lF86TIXXwkJACP
    ugSpCwCxAoGBAP1dWKl4fCjO09TKQ/vML9daNJOfAF3onsNFvawDFcBbGguxf7yP
    oVadAfb1WfVnnpJqIq9GbSAmkInei31yjcySZ/1Z9vfjCwYvCgFHR58xHH5QKtzg
    y9Jo3oBtSyYxd0Ggm8MWZTAlPgFs+GAMxcW1zluFCQAIK7KVEMoBEwk1AoGBAM/D
    RRHNhrvJjD6LGLjfTvZcEhvjZ5627nmKpzt1X9JNhrON9n+rn6YcA0oKKoUEYRYT
    IUGJM1PsUUPgyBU/w8UccMDKSnck2ZOpKU7Ikp9DsyE3V6OsiiTeEiT2dNQpmomq
    Q7sntqliXHXrmKH03R/7ZQwxXXwcCctZSp+6fiD9AoGAabIjZq+IvE1sOX0X11db
    Le/Htz3BnWuJr9TMR5IR5OkceHxX2YXhvIxLYYcBPEs578KvLYenxp3P9nQMpQzA
    8vKwxxRc3xSsaKv+9IGT82k9hcRT3Uk6PlDZYaI2k3xXT918nWoeVHN05otbIlax
    usUZjTx2gLjn4dwl4N+J3XECgYAbBo6cgzysfso0dImRutKdr1pXsFwRREB/JO8e
    B+WgCJ+mCahv8RZCWFCBOBNR3ED4yyI/USaRGyNzDfFY+kNwB4QPQAExwGRhFdce
    vW59MyRBBN7slowdwZlgn4KQ+px0neZTmRXksLvQRwZCwwRknaIGVQGRHGCVyBax
    8mNnzQKBgQCKO+/eQCPa6SdAHc2Gm+FDSSHi44at5lcmL1De+NXweXvLsHpP39oU
    nLTMgvgAiiXwv0iYJ90Uc7LmsUKdQw4SkYmR4m/F4B0kjUMcSAt1s8fPzdOnmeGm
    66Xyp7ozCgft2+26UcEQAPG0Ifk+ycsRL6oMF5Nup7WOEofJX9bmdA==
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      encrypted_key: "<%= ENV['PRODUCTION_KEY1'] %>"
      iv:            "rZFJRSlCCSH+A6YfH0RTFA=="
      cipher_name:   aes-256-cbc
      # Base64 encode encrypted data without newlines
      encoding:      :base64strict
      version:       1
